### ISSUE TITLE
add item/switch/accessoire

### ISSUE THREAD

**Issue by theo-69** [Maxmudjon/homebridge-mijia#12]
After i install the plug-in are all mijia items (switches, sensors etc.) show up on its own or do i have to ad them in my config? Sorry I am newbee and trying to start...

**Comment by timh1004** [comment]
You only have to add the add the gateway to the platforms in your config file. Then it should show all your devices in HomeKit which you have configured in the Mi Home App on your smartphone.

**Comment by theo-69** [comment]
i did this, however there are no items show in homekit
