### ISSUE TITLE
gateway ID

### ISSUE THREAD

**Issue by theo-69** [Maxmudjon/homebridge-mijia#16]
The installation is not possible anymore the app looks diffrent now, no chinese and cant find the information needed for the config.sys
![img_1311](https://cloud.githubusercontent.com/assets/28484958/26496565/53e990ca-4228-11e7-8e6b-12364992a601.PNG)

**Comment by licuhui** [comment]
Choose about，In the bottom of the screen continuous press, will pop up the desired information
