### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by sangkooki** [Maxmudjon/homebridge-mijia#3]
Hi
I use 
/usr/lib/node_modules/homebridge-mijia

instead /usr/local/lib...

So this message produced

/usr/lib/node_modules/homebridge-mijia/lib/MiJiaPlatform.js:180
May 06 12:42:54 raspberrypi homebridge[31524]: if (err) throw err
May 06 12:42:54 raspberrypi homebridge[31524]: ^
May 06 12:42:54 raspberrypi homebridge[31524]: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/homebridge-mijia/158d0000

**Comment by Maxmudjon** [comment]
I upgraded to version 1.2.78. Try to update
