### ISSUE TITLE
Battery status service

### ISSUE THREAD

**Issue by iCarl** [Maxmudjon/homebridge-mijia#7]
Which devices are compatible with the battery status service?

**Comment by Maxmudjon** [comment]
![mijia-body-sensor-200x200](https://cloud.githubusercontent.com/assets/23142922/25892806/052a5230-358f-11e7-90ff-68d081d7932b.jpg)
![mijia-door-window-sensor-200x200](https://cloud.githubusercontent.com/assets/23142922/25892807/052f4506-358f-11e7-8733-f415d559dcc3.jpg)
![mijia-temperature-humidity-sensor-200x200](https://cloud.githubusercontent.com/assets/23142922/25892808/05346324-358f-11e7-9034-39d000de9ea5.jpg)
![mijia-wireless-switch-200x200](https://cloud.githubusercontent.com/assets/23142922/25892809/05556560-358f-11e7-91cb-1d68cff4a710.jpg)

**Comment by Maxmudjon** [comment]
Future will add it
![mijia-light-control-slim-200x200](https://cloud.githubusercontent.com/assets/23142922/25893386/0965046a-3591-11e7-9b3c-1d8f6a3a2aae.jpg)

**Comment by iCarl** [comment]
Will you add support for the upcomming Aqara devices? 
Like the new curtain motor?

**Comment by Maxmudjon** [comment]
I ordered a motor for curtains from Agara. When will come we will look
